// PSY101 Key Term Definitions
const TERM_DEFINITIONS = {
    // Introduction to Psychology
    "Introspection": "A method of self-observation where individuals examine and report their own conscious thoughts, feelings, and sensations.",
    "Structuralism": "An early school of psychology founded by Wilhelm Wundt and Edward Titchener that aimed to identify the basic elements of consciousness through introspection.",
    "Functionalism": "A school of psychology founded by William James that focused on how mental processes help organisms adapt to their environment.",
    "Psychoanalysis": "A theory and therapeutic approach developed by Sigmund Freud emphasizing the role of unconscious processes in shaping behavior.",
    "Behaviorism": "A school of psychology founded by John B. Watson that focuses only on observable, measurable behavior rather than mental processes.",
    "Humanism": "A psychological perspective that emphasizes free will, personal growth, and the inherent goodness of human beings.",
    "Cognitive Psychology": "The scientific study of mental processes including thinking, learning, memory, attention, perception, and problem-solving.",
    "Biopsychosocial Model": "An approach that considers biological, psychological, and social factors as interconnected influences on health and behavior.",
    "Eclectic Approach": "Using techniques and ideas from multiple psychological perspectives based on what works best for each situation.",
    "Nature vs. Nurture": "The debate over the relative contributions of genetic inheritance (nature) and environmental factors (nurture) to human development.",
    "Reductionism": "The practice of analyzing complex phenomena by breaking them down into smaller, simpler components.",
    "Holism": "The idea that systems should be studied as wholes rather than just collections of parts.",
    "Independent Variable": "The factor that is manipulated or changed by the researcher in an experiment.",
    "Dependent Variable": "The factor that is measured in an experiment; it may change in response to the independent variable.",
    "Control Group": "A group in an experiment that does not receive the treatment, used as a baseline for comparison.",
    "Random Assignment": "Assigning participants to experimental groups by chance to ensure groups are equivalent at the start.",
    "Double-Blind": "An experimental procedure where neither participants nor researchers know who is in the control or experimental group.",
    "Correlation": "A statistical measure of the relationship between two variables, ranging from -1.0 to +1.0.",
    "Validity": "The extent to which a test or study measures what it claims to measure.",
    "Reliability": "The consistency of a measure; a reliable test produces similar results under consistent conditions.",
    "Informed Consent": "Participants' agreement to participate in research after being told about the study's purpose, procedures, risks, and benefits.",
    "Debriefing": "Explaining the true purpose of a study to participants after their participation is complete.",
    "Confidentiality": "Protecting participants' personal information and ensuring their data remains private.",
    "IRB": "Institutional Review Board - a committee that reviews research proposals to ensure ethical treatment of participants.",
    "APA Ethics Code": "The American Psychological Association's guidelines for ethical conduct in research and practice.",
    "Deception": "Misleading participants about the true purpose of a study, which must be justified and followed by debriefing.",

    // Biological Psychology
    "Action Potential": "An electrical signal that travels along an axon when a neuron fires, caused by ion movement across the membrane.",
    "Synapse": "The small gap between neurons where neurotransmitters are released to communicate signals from one neuron to another.",
    "Neurotransmitter": "Chemical messengers that cross synapses to transmit signals between neurons.",
    "Myelin Sheath": "A fatty insulating layer around axons that speeds up neural transmission.",
    "Threshold": "The minimum level of stimulation required to trigger a neural impulse (action potential).",
    "Refractory Period": "A brief period after firing during which a neuron cannot fire again.",
    "Glial Cells": "Non-neuronal cells in the nervous system that support, protect, and nourish neurons.",
    "Dopamine": "A neurotransmitter involved in reward, motivation, movement, and pleasure; implicated in addiction and Parkinson's disease.",
    "Serotonin": "A neurotransmitter that regulates mood, sleep, appetite, and body temperature; low levels linked to depression.",
    "GABA": "Gamma-aminobutyric acid - the main inhibitory neurotransmitter that reduces neural activity; involved in anxiety regulation.",
    "Glutamate": "The main excitatory neurotransmitter in the brain, involved in learning and memory.",
    "Acetylcholine": "A neurotransmitter involved in muscle movement, attention, and memory; depleted in Alzheimer's disease.",
    "Endorphins": "Natural painkillers produced by the brain that also create feelings of pleasure and well-being.",
    "Agonist": "A drug or chemical that mimics or enhances the action of a neurotransmitter.",
    "Antagonist": "A drug or chemical that blocks or reduces the action of a neurotransmitter.",
    "Cerebral Cortex": "The outer layer of the brain responsible for higher cognitive functions like thinking, language, and consciousness.",
    "Limbic System": "A group of brain structures (including amygdala and hippocampus) involved in emotion, memory, and motivation.",
    "Hippocampus": "A brain structure critical for forming new explicit memories and spatial navigation.",
    "Amygdala": "An almond-shaped brain structure involved in processing emotions, especially fear and aggression.",
    "Prefrontal Cortex": "The front part of the frontal lobe involved in decision-making, planning, and impulse control.",
    "Corpus Callosum": "A thick band of nerve fibers connecting the left and right hemispheres of the brain.",
    "Plasticity": "The brain's ability to change and reorganize by forming new neural connections throughout life.",
    "CNS": "Central Nervous System - the brain and spinal cord.",
    "PNS": "Peripheral Nervous System - all nerves outside the brain and spinal cord.",
    "Autonomic": "The division of the PNS that controls involuntary functions like heart rate and digestion.",
    "Sympathetic": "The branch of the autonomic nervous system that activates the 'fight-or-flight' response.",
    "Parasympathetic": "The branch of the autonomic nervous system that calms the body ('rest and digest').",
    "Hormones": "Chemical messengers secreted by endocrine glands that travel through blood to affect target organs.",
    "Endocrine System": "The body's chemical communication system using hormones secreted by glands.",
    "Heritability": "The proportion of variation in a trait within a population that is attributable to genetic differences.",
    "Twin Studies": "Research comparing identical and fraternal twins to estimate genetic vs. environmental influences on traits.",
    "Epigenetics": "The study of how environmental factors can affect gene expression without changing DNA sequence.",
    "Genotype": "An individual's genetic makeup or complete set of genes.",
    "Phenotype": "The observable characteristics of an individual resulting from genes and environment.",
    "Behavioral Genetics": "The study of how genes and environment influence individual differences in behavior.",

    // Sensation & Perception
    "Transduction": "The conversion of one form of energy (like light or sound) into neural signals.",
    "Absolute Threshold": "The minimum amount of stimulation needed to detect a stimulus 50% of the time.",
    "Difference Threshold": "The smallest difference between two stimuli that can be detected 50% of the time (also called JND).",
    "Weber's Law": "The principle that the just noticeable difference is a constant proportion of the original stimulus.",
    "Signal Detection": "A theory explaining how we detect signals amid background noise, considering sensitivity and decision criteria.",
    "Sensory Adaptation": "Decreased sensitivity to a constant, unchanging stimulus over time.",
    "Retina": "The light-sensitive inner surface of the eye containing photoreceptors (rods and cones).",
    "Rods": "Photoreceptors in the retina that detect dim light and peripheral vision but not color.",
    "Cones": "Photoreceptors in the retina that detect color and fine detail, concentrated in the fovea.",
    "Fovea": "The central area of the retina with the highest concentration of cones, providing sharpest vision.",
    "Optic Nerve": "The nerve that carries visual information from the retina to the brain.",
    "Trichromatic Theory": "The theory that color vision depends on three types of cones sensitive to red, green, and blue light.",
    "Opponent-Process Theory": "The theory that color vision involves opposing pairs: red-green, blue-yellow, and black-white.",
    "Cochlea": "A snail-shaped, fluid-filled structure in the inner ear where sound waves are converted to neural signals.",
    "Hair Cells": "Sensory receptors in the cochlea that convert sound vibrations into neural impulses.",
    "Basilar Membrane": "A membrane in the cochlea that vibrates in response to sound and contains hair cells.",
    "Place Theory": "The theory that pitch is determined by which location on the basilar membrane vibrates most.",
    "Frequency Theory": "The theory that pitch is determined by the rate at which the entire basilar membrane vibrates.",
    "Decibels": "A unit for measuring the intensity (loudness) of sound.",
    "Olfaction": "The sense of smell.",
    "Gustation": "The sense of taste.",
    "Kinesthesis": "The sense of body position and movement of body parts relative to each other.",
    "Vestibular Sense": "The sense of balance and spatial orientation, located in the inner ear.",
    "Gate-Control Theory": "The theory that pain signals can be blocked at the spinal cord by other sensory input or brain signals.",
    "Proprioception": "The sense of the position and movement of one's own body parts.",
    "Gestalt": "A school of psychology emphasizing that we perceive objects as organized wholes rather than separate parts.",
    "Figure-Ground": "The perceptual organization of visual information into objects (figures) and their surroundings (ground).",
    "Depth Cues": "Visual signals used to perceive distance, including binocular cues (two eyes) and monocular cues (one eye).",
    "Perceptual Constancy": "The tendency to perceive objects as stable despite changes in sensory input (size, shape, color).",
    "Bottom-Up": "Data-driven processing that begins with sensory information and builds up to perception.",
    "Top-Down": "Concept-driven processing where expectations and knowledge influence perception.",
    "Perceptual Set": "A mental predisposition to perceive things in a certain way based on expectations.",

    // Consciousness
    "Selective Attention": "The ability to focus on one stimulus while ignoring others.",
    "Inattentional Blindness": "Failure to notice fully visible objects when attention is focused elsewhere.",
    "Change Blindness": "Failure to notice changes in a visual scene, especially during brief interruptions.",
    "Cocktail Party Effect": "The ability to focus on one voice among many and still notice personally relevant information elsewhere.",
    "Automatic Processing": "Unconscious, effortless encoding of information (like time, space, and frequency).",
    "Circadian Rhythm": "The 24-hour biological cycle that regulates sleep-wake patterns and other bodily functions.",
    "NREM": "Non-rapid eye movement sleep - the sleep stages (1-3) without rapid eye movements or vivid dreams.",
    "REM": "Rapid eye movement sleep - a sleep stage with vivid dreams, muscle paralysis, and brain activity similar to waking.",
    "Delta Waves": "Large, slow brain waves associated with deep sleep (Stage 3 NREM).",
    "Sleep Spindles": "Bursts of brain activity during Stage 2 NREM sleep, thought to help with memory consolidation.",
    "Melatonin": "A hormone released by the pineal gland that helps regulate sleep-wake cycles.",
    "Manifest Content": "The remembered storyline of a dream (what the dream appears to be about).",
    "Latent Content": "According to Freud, the hidden, unconscious meaning of a dream.",
    "Activation-Synthesis": "A theory that dreams result from the brain's attempt to make sense of random neural activity during REM sleep.",
    "Lucid Dreaming": "Being aware that you are dreaming while still in the dream, sometimes with ability to control it.",
    "REM Rebound": "The tendency to have longer and more frequent REM sleep after being deprived of it.",
    "Insomnia": "A sleep disorder characterized by difficulty falling asleep, staying asleep, or waking too early.",
    "Sleep Apnea": "A disorder involving repeated breathing interruptions during sleep, causing frequent awakenings.",
    "Narcolepsy": "A disorder characterized by sudden, uncontrollable sleep attacks during waking hours.",
    "Cataplexy": "Sudden loss of muscle tone triggered by strong emotions, often associated with narcolepsy.",
    "Somnambulism": "Sleepwalking - walking or performing other behaviors while asleep, typically during deep NREM sleep.",
    "Parasomnia": "Abnormal behaviors or experiences during sleep, such as sleepwalking or night terrors.",
    "Psychoactive Drugs": "Chemicals that alter perception, mood, or behavior by affecting neurotransmitter activity.",
    "Tolerance": "The need for increasing amounts of a drug to achieve the same effect.",
    "Withdrawal": "Physical and psychological symptoms that occur when a drug is discontinued after prolonged use.",
    "Depressants": "Drugs that slow brain activity and reduce neural transmission (e.g., alcohol, barbiturates).",
    "Stimulants": "Drugs that increase brain activity and neural transmission (e.g., caffeine, cocaine, amphetamines).",
    "Hallucinogens": "Drugs that distort perception and evoke sensory experiences without external stimuli (e.g., LSD).",
    "Hypnosis": "A state of focused attention and heightened suggestibility.",

    // Learning
    "US": "Unconditioned Stimulus - a stimulus that naturally triggers a response without prior learning.",
    "UR": "Unconditioned Response - an unlearned, automatic response to an unconditioned stimulus.",
    "CS": "Conditioned Stimulus - a previously neutral stimulus that, after association with a US, triggers a response.",
    "CR": "Conditioned Response - a learned response to a previously neutral (now conditioned) stimulus.",
    "Acquisition": "The initial learning stage in conditioning when a response is established.",
    "Extinction": "The gradual weakening of a conditioned response when the CS is repeatedly presented without the US.",
    "Spontaneous Recovery": "The reappearance of an extinguished conditioned response after a rest period.",
    "Generalization": "The tendency to respond similarly to stimuli that resemble the conditioned stimulus.",
    "Discrimination": "The learned ability to distinguish between similar stimuli and respond only to the specific CS.",
    "Reinforcement": "Any consequence that strengthens a behavior, making it more likely to recur.",
    "Punishment": "Any consequence that weakens a behavior, making it less likely to recur.",
    "Shaping": "Reinforcing successive approximations toward a desired behavior.",
    "Schedules of Reinforcement": "Patterns defining how often and when reinforcement is delivered (continuous or partial).",
    "Token Economy": "A behavior modification system where tokens earned for desired behaviors can be exchanged for rewards.",
    "Modeling": "Learning by observing and imitating others' behavior.",
    "Vicarious Reinforcement": "Learning from observing others being reinforced or punished for their behavior.",
    "Mirror Neurons": "Brain cells that fire both when performing an action and when observing others perform that action.",
    "Bandura": "Albert Bandura - psychologist known for social learning theory and the Bobo doll experiments.",
    "Social Learning Theory": "The theory that learning occurs through observation, imitation, and modeling of others.",
    "Latent Learning": "Learning that occurs without obvious reinforcement and is not demonstrated until there is motivation to do so.",
    "Cognitive Map": "A mental representation of a physical space or environment.",
    "Insight": "A sudden realization of a problem's solution, without trial and error.",
    "Learned Helplessness": "A passive resignation produced by repeated exposure to unavoidable negative events.",
    "Biological Preparedness": "The innate tendency to more easily learn some associations than others (evolutionary advantage).",

    // Memory
    "Sensory Memory": "The brief, initial recording of sensory information in the memory system (lasting only seconds).",
    "Short-Term Memory": "Memory that holds a small amount of information for a brief time (about 20-30 seconds).",
    "Long-Term Memory": "The relatively permanent and unlimited storage of information.",
    "Working Memory": "A newer understanding of short-term memory that focuses on conscious, active processing of information.",
    "Central Executive": "The component of working memory that directs attention and coordinates information processing.",
    "Chunking": "Organizing information into meaningful units to increase short-term memory capacity.",
    "Mnemonics": "Memory aids using vivid imagery or organizational devices to enhance recall.",
    "Elaborative Rehearsal": "Encoding information by connecting it to existing knowledge and making it meaningful.",
    "Spacing Effect": "The tendency for distributed practice to produce better long-term retention than massed practice.",
    "Encoding Specificity": "The principle that cues present at encoding are effective retrieval cues.",
    "Explicit Memory": "Memory of facts and experiences that one can consciously know and declare (declarative memory).",
    "Implicit Memory": "Memory for skills and conditioned responses that is retrieved without conscious recollection.",
    "Semantic": "Memory for general facts and knowledge not tied to personal experience.",
    "Episodic": "Memory for personally experienced events (autobiographical memory).",
    "Procedural": "Memory for motor skills and habits (how to do things).",
    "LTP": "Long-term potentiation - the strengthening of synaptic connections with repeated activation, basis for memory.",
    "Recall": "A measure of memory in which information must be retrieved with minimal cues.",
    "Recognition": "A measure of memory in which previously learned information is identified from options.",
    "Retrieval Cues": "Stimuli that help access stored memories.",
    "Proactive Interference": "Older information interfering with the learning of new information.",
    "Retroactive Interference": "New information interfering with the recall of older information.",
    "Decay": "The fading of memories over time if not accessed or rehearsed.",
    "Misinformation Effect": "Incorporating misleading information into memory of an event after it occurs.",
    "Source Monitoring": "Attributing memories to their correct source; errors lead to false memories.",
    "False Memory": "A memory of something that did not actually happen, often created through suggestion.",
    "Flashbulb Memory": "A vivid, long-lasting memory of an emotionally significant event (not always accurate).",
    "Schema": "A mental framework or concept that organizes and interprets information.",

    // Cognition & Intelligence
    "Concepts": "Mental categories used to group objects, events, and ideas with common features.",
    "Prototypes": "The best or most typical example of a category.",
    "Algorithms": "Step-by-step procedures that guarantee a solution to a problem.",
    "Heuristics": "Mental shortcuts or rules of thumb that allow quick decision-making but may lead to errors.",
    "Cognitive Biases": "Systematic errors in thinking that affect judgments and decisions.",
    "Mental Set": "The tendency to approach problems using strategies that have worked in the past.",
    "Functional Fixedness": "The inability to see objects as having functions beyond their typical use.",
    "Divergent Thinking": "Thinking that explores many possible solutions; associated with creativity.",
    "Convergent Thinking": "Thinking that focuses on a single correct solution to a problem.",
    "Incubation": "A break from problem-solving that can lead to sudden insight upon returning to the problem.",
    "Phonemes": "The smallest units of sound in a language.",
    "Morphemes": "The smallest units of meaning in a language (words, prefixes, suffixes).",
    "Syntax": "The grammatical rules for combining words into phrases and sentences.",
    "Semantics": "The rules for deriving meaning from words and sentences.",
    "LAD": "Language Acquisition Device - Chomsky's hypothesized innate ability to learn language.",
    "Linguistic Relativity": "The hypothesis that language influences thought and perception (Sapir-Whorf hypothesis).",
    "Broca's Area": "A brain region in the left frontal lobe involved in speech production.",
    "Wernicke's Area": "A brain region in the left temporal lobe involved in language comprehension.",
    "g Factor": "Spearman's concept of general intelligence underlying all mental abilities.",
    "Multiple Intelligences": "Gardner's theory that intelligence consists of several distinct abilities.",
    "Emotional Intelligence": "The ability to perceive, understand, manage, and use emotions effectively.",
    "IQ": "Intelligence quotient - a score representing cognitive ability relative to one's age group.",
    "Stanford-Binet": "A widely used intelligence test originally developed by Alfred Binet.",
    "WAIS": "Wechsler Adult Intelligence Scale - the most widely used intelligence test for adults.",
    "Flynn Effect": "The observed rise in average IQ scores over generations.",
    "Stereotype Threat": "Anxiety about confirming negative stereotypes that can impair performance.",
    "Cultural Bias": "The tendency for tests to favor certain cultural groups over others.",

    // Human Development
    "Germinal": "The first stage of prenatal development (conception to 2 weeks) involving cell division.",
    "Embryonic": "The prenatal stage from weeks 2-8 when major organs and body systems form.",
    "Fetal": "The prenatal stage from week 9 to birth characterized by growth and maturation.",
    "Teratogens": "Harmful agents (drugs, viruses, chemicals) that can cause birth defects during prenatal development.",
    "Fetal Alcohol Syndrome": "Physical and cognitive abnormalities caused by maternal alcohol consumption during pregnancy.",
    "Placenta": "The organ connecting the developing fetus to the mother's uterine wall for nutrient exchange.",
    "Object Permanence": "The understanding that objects continue to exist even when not visible (develops around 8 months).",
    "Attachment": "The emotional bond between an infant and caregiver.",
    "Secure Attachment": "An attachment style in which infants use the caregiver as a safe base for exploration.",
    "Strange Situation": "Ainsworth's procedure for assessing infant attachment styles.",
    "Temperament": "An infant's characteristic emotional reactivity and intensity.",
    "Schemas": "Mental frameworks that organize knowledge and guide information processing.",
    "Assimilation": "Interpreting new experiences in terms of existing schemas.",
    "Accommodation": "Modifying existing schemas to incorporate new information.",
    "Conservation": "The understanding that properties like quantity remain the same despite changes in appearance.",
    "Zone of Proximal Development": "The gap between what a learner can do alone and what they can do with guidance.",
    "Theory of Mind": "The ability to understand that others have thoughts and beliefs different from one's own.",
    "Puberty": "The period of sexual maturation during which a person becomes capable of reproduction.",
    "Identity": "One's sense of self; Erikson's adolescent developmental task is forming a clear identity.",
    "Formal Operations": "Piaget's final stage when abstract, logical, and hypothetical thinking develops.",
    "Moral Development": "The growth of values and ethical principles, studied by Kohlberg using moral dilemmas.",
    "Personal Fable": "Adolescents' belief that their experiences and feelings are unique.",
    "Imaginary Audience": "Adolescents' assumption that others are constantly watching and judging them.",
    "Crystallized Intelligence": "Accumulated knowledge and verbal skills that increase with age.",
    "Fluid Intelligence": "The ability to solve novel problems and think abstractly; tends to decline with age.",
    "Generativity": "Erikson's middle adulthood stage focusing on contributing to future generations.",
    "Ego Integrity": "Erikson's late adulthood stage involving reflection on life with a sense of fulfillment.",
    "Social Clock": "Cultural expectations about the appropriate timing of life events (marriage, career, etc.).",

    // Motivation & Emotion
    "Homeostasis": "The body's tendency to maintain a stable internal environment.",
    "Arousal": "A state of physiological activation or alertness.",
    "Incentive": "A positive or negative environmental stimulus that motivates behavior.",
    "Hierarchy of Needs": "Maslow's pyramid of human needs from basic physiological to self-actualization.",
    "Intrinsic Motivation": "The desire to engage in behavior for its own sake, for internal satisfaction.",
    "Extrinsic Motivation": "The desire to engage in behavior because of external rewards or pressures.",
    "Ghrelin": "A hormone secreted by the stomach that signals hunger to the brain.",
    "Leptin": "A hormone secreted by fat cells that signals satiety to the brain.",
    "Hypothalamus": "A brain structure that regulates basic drives including hunger, thirst, and body temperature.",
    "Set Point": "The weight level at which the body tends to remain stable.",
    "Anorexia Nervosa": "An eating disorder characterized by self-starvation and extreme fear of weight gain.",
    "Bulimia Nervosa": "An eating disorder characterized by binge eating followed by purging.",
    "Binge-Eating Disorder": "An eating disorder involving recurrent episodes of uncontrolled eating without purging.",
    "Achievement Motivation": "The desire to accomplish something and meet standards of excellence.",
    "Overjustification": "The effect of external rewards reducing intrinsic motivation for an activity.",
    "Growth Mindset": "The belief that abilities can be developed through effort and learning.",
    "Self-Efficacy": "One's belief in their ability to succeed in specific situations.",
    "Goal Setting": "The process of establishing specific, measurable objectives to guide behavior.",
    "James-Lange Theory": "The theory that emotions result from awareness of physiological responses.",
    "Cannon-Bard Theory": "The theory that physiological arousal and emotional experience occur simultaneously.",
    "Two-Factor Theory": "Schachter-Singer's theory that emotion requires physiological arousal plus cognitive interpretation.",
    "Cognitive Appraisal": "The process of evaluating a stimulus that determines emotional response.",
    "Facial Feedback": "The hypothesis that facial expressions can influence emotional experience.",
    "Basic Emotions": "Universal emotional expressions identified across cultures (happiness, sadness, fear, anger, surprise, disgust).",
    "Display Rules": "Cultural norms governing the appropriate expression of emotions.",
    "Subjective Well-Being": "Self-perceived happiness and satisfaction with life.",
    "Hedonic Treadmill": "The tendency to return to a baseline level of happiness despite positive or negative events.",

    // Personality
    "Id": "In Freud's theory, the unconscious psychic energy seeking immediate gratification.",
    "Ego": "In Freud's theory, the mostly conscious executive part mediating between id, superego, and reality.",
    "Superego": "In Freud's theory, the internalized ideals and conscience.",
    "Unconscious": "According to psychodynamic theory, thoughts, memories, and feelings outside awareness.",
    "Defense Mechanisms": "Unconscious strategies the ego uses to reduce anxiety (repression, denial, projection, etc.).",
    "Psychosexual Stages": "Freud's stages of development (oral, anal, phallic, latency, genital) focused on erogenous zones.",
    "Self-Actualization": "The fulfillment of one's potential, the highest need in Maslow's hierarchy.",
    "Self-Concept": "A person's understanding and evaluation of who they are.",
    "Unconditional Positive Regard": "Accepting and valuing a person regardless of their behavior.",
    "Conditions of Worth": "Standards we must meet to receive acceptance and approval from others.",
    "Real Self": "A person's actual experience of who they are.",
    "Ideal Self": "A person's concept of who they would like to be.",
    "Traits": "Characteristic patterns of behavior and thinking that are relatively stable across situations.",
    "Big Five": "The five major personality dimensions: Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism.",
    "OCEAN": "Acronym for the Big Five personality traits.",
    "Openness": "A Big Five trait reflecting imagination, creativity, and openness to new experiences.",
    "Conscientiousness": "A Big Five trait reflecting organization, dependability, and self-discipline.",
    "Extraversion": "A Big Five trait reflecting sociability, assertiveness, and positive emotions.",
    "Agreeableness": "A Big Five trait reflecting cooperativeness, trust, and helpfulness.",
    "Neuroticism": "A Big Five trait reflecting emotional instability, anxiety, and moodiness.",
    "Reciprocal Determinism": "Bandura's concept that behavior, cognition, and environment mutually influence each other.",
    "Locus of Control": "The perception of whether outcomes are controlled by internal factors or external forces.",
    "Social Learning": "Learning through observing and imitating others' behavior.",
    "MMPI": "Minnesota Multiphasic Personality Inventory - a widely used clinical personality assessment.",
    "NEO-PI-R": "A personality inventory measuring the Big Five personality traits.",
    "Rorschach": "A projective test using inkblots to assess personality.",
    "TAT": "Thematic Apperception Test - a projective test where people create stories about ambiguous pictures.",
    "Projective Tests": "Personality assessments using ambiguous stimuli to reveal unconscious processes.",

    // Social Psychology
    "Attribution": "The process of explaining the causes of behavior.",
    "Fundamental Attribution Error": "The tendency to overestimate dispositional and underestimate situational factors in others' behavior.",
    "Self-Serving Bias": "The tendency to attribute success to internal factors and failure to external factors.",
    "Cognitive Dissonance": "The discomfort felt when holding conflicting beliefs or when behavior conflicts with attitudes.",
    "Attitudes": "Evaluative reactions (positive or negative) toward people, objects, or ideas.",
    "Conformity": "Adjusting one's behavior or thinking to match a group standard.",
    "Obedience": "Compliance with direct commands from an authority figure.",
    "Compliance": "Behavior change in response to explicit or implicit requests from others.",
    "Normative Influence": "Conformity resulting from the desire to be liked and accepted.",
    "Milgram": "Stanley Milgram - psychologist known for famous obedience experiments.",
    "Groupthink": "The tendency for group members to suppress dissent in favor of group harmony.",
    "Social Facilitation": "Improved performance on simple tasks in the presence of others.",
    "Social Loafing": "The tendency to exert less effort in a group than when working alone.",
    "Deindividuation": "Loss of self-awareness and self-restraint in group situations.",
    "Group Polarization": "The tendency for group discussion to strengthen the dominant position held by group members.",
    "Prejudice": "A negative attitude toward a group and its members.",
    "Stereotype": "A generalized belief about a group of people.",
    "Discrimination": "Unjustifiable negative behavior toward a group and its members.",
    "In-group Bias": "The tendency to favor one's own group over other groups.",
    "Scapegoating": "Blaming an innocent person or group for one's own problems.",
    "Contact Hypothesis": "The idea that contact between groups under positive conditions can reduce prejudice.",
    "Proximity": "Physical or geographical nearness, which increases attraction.",
    "Mere Exposure": "The phenomenon that repeated exposure to something increases liking for it.",
    "Similarity": "The extent to which people share attitudes, values, and interests; predicts attraction.",
    "Triangular Theory": "Sternberg's theory that love consists of intimacy, passion, and commitment.",
    "Equity Theory": "The theory that relationships are satisfying when both partners contribute equally.",
    "Altruism": "Unselfish regard for the welfare of others.",
    "Bystander Effect": "The tendency for people to be less likely to help when others are present.",
    "Diffusion of Responsibility": "The phenomenon where responsibility is shared among group members, reducing individual action.",
    "Aggression": "Physical or verbal behavior intended to harm someone.",
    "Social Norms": "Unwritten rules about how members of a society should behave.",

    // Psychological Disorders
    "DSM-5": "Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition - the standard classification system.",
    "Medical Model": "The concept that psychological disorders are illnesses with biological causes.",
    "Diathesis-Stress": "The theory that disorders result from a genetic predisposition combined with environmental stress.",
    "Labeling": "The process of identifying and naming a disorder, which can affect perception and treatment.",
    "Stigma": "Negative attitudes and discrimination against people with mental disorders.",
    "GAD": "Generalized Anxiety Disorder - persistent, excessive worry about many things.",
    "Panic Disorder": "An anxiety disorder marked by recurring panic attacks and fear of future attacks.",
    "Phobia": "An intense, irrational fear of a specific object or situation.",
    "Social Anxiety": "Intense fear of social situations where one might be judged or embarrassed.",
    "Agoraphobia": "Fear of places or situations where escape might be difficult or help unavailable.",
    "Comorbidity": "The presence of two or more disorders in the same person.",
    "Obsessions": "Unwanted, intrusive thoughts that cause anxiety.",
    "Compulsions": "Repetitive behaviors or mental acts performed to reduce anxiety from obsessions.",
    "OCD": "Obsessive-Compulsive Disorder - a condition involving obsessions and/or compulsions.",
    "Body Dysmorphic Disorder": "Preoccupation with perceived flaws in physical appearance that others don't notice.",
    "Hoarding": "Persistent difficulty discarding possessions regardless of their value.",
    "PTSD": "Post-Traumatic Stress Disorder - a condition following trauma with flashbacks, avoidance, and hyperarousal.",
    "Trauma": "A deeply distressing or disturbing experience.",
    "Flashbacks": "Intrusive re-experiencing of a traumatic event as if it were happening again.",
    "Hyperarousal": "A state of increased alertness, anxiety, and startle response following trauma.",
    "Acute Stress Disorder": "A short-term condition following trauma, similar to but briefer than PTSD.",
    "Resilience": "The ability to recover and adapt well in the face of adversity or trauma.",
    "Major Depression": "A mood disorder characterized by persistent sadness, loss of interest, and other symptoms.",
    "Bipolar Disorder": "A mood disorder involving alternating episodes of depression and mania.",
    "Mania": "A mood state characterized by elevated mood, increased energy, and decreased need for sleep.",
    "Dysthymia": "Persistent depressive disorder - chronic, mild depression lasting at least two years.",
    "Cognitive Triad": "Beck's concept of negative views about self, world, and future in depression.",
    "Hallucinations": "Sensory experiences without external stimulation (hearing voices, seeing things).",
    "Delusions": "False beliefs that persist despite contradictory evidence.",
    "Positive Symptoms": "Symptoms of schizophrenia that represent additions to normal behavior (hallucinations, delusions).",
    "Negative Symptoms": "Symptoms of schizophrenia that represent reductions in normal behavior (flat affect, avolition).",
    "Dopamine Hypothesis": "The theory that schizophrenia involves excess dopamine activity.",
    "Personality Disorders": "Enduring, inflexible patterns of behavior that cause distress or impairment.",
    "Cluster A/B/C": "The three groups of personality disorders: odd/eccentric, dramatic/erratic, anxious/fearful.",
    "Antisocial": "A personality disorder characterized by disregard for and violation of others' rights.",
    "Borderline": "A personality disorder marked by instability in relationships, self-image, and emotions.",
    "Narcissistic": "A personality disorder characterized by grandiosity, need for admiration, and lack of empathy.",

    // Therapy & Treatment
    "Psychotherapy": "Treatment of psychological disorders through psychological rather than biomedical means.",
    "Therapeutic Alliance": "The collaborative, trusting relationship between therapist and client.",
    "Evidence-Based": "Treatments that have been scientifically tested and shown to be effective.",
    "Eclectic": "An approach that draws from multiple therapeutic orientations.",
    "Mental Health Professional": "A trained provider of psychological services (psychologist, psychiatrist, counselor, etc.).",
    "Free Association": "A psychoanalytic technique where clients say whatever comes to mind.",
    "Dream Analysis": "A psychoanalytic technique for revealing unconscious content through dream interpretation.",
    "Transference": "In psychoanalysis, the client's unconscious redirection of feelings onto the therapist.",
    "Resistance": "In psychoanalysis, the blocking of anxiety-laden material from conscious awareness.",
    "Interpersonal Therapy": "A brief therapy focusing on improving current relationships and social skills.",
    "Client-Centered": "Rogers' humanistic therapy emphasizing unconditional positive regard, empathy, and genuineness.",
    "Genuineness": "The therapist's authentic, honest presentation of self in therapy.",
    "Existential": "A therapy approach focusing on meaning, responsibility, and mortality.",
    "Systematic Desensitization": "A behavioral technique pairing relaxation with gradual exposure to feared stimuli.",
    "Exposure Therapy": "A behavioral treatment involving confrontation with feared stimuli.",
    "Flooding": "An intensive exposure therapy technique with prolonged exposure to feared stimuli.",
    "Aversion Therapy": "A behavioral technique pairing unwanted behavior with unpleasant stimuli.",
    "CBT": "Cognitive-Behavioral Therapy - combining cognitive restructuring with behavioral techniques.",
    "Cognitive Distortions": "Irrational thought patterns that contribute to negative emotions (e.g., all-or-nothing thinking).",
    "REBT": "Rational Emotive Behavior Therapy - Ellis's approach to disputing irrational beliefs.",
    "Automatic Thoughts": "Spontaneous, often negative thoughts that pop into awareness.",
    "Cognitive Restructuring": "Identifying and changing maladaptive thought patterns.",
    "SSRIs": "Selective Serotonin Reuptake Inhibitors - antidepressants that increase serotonin availability.",
    "Antipsychotics": "Medications that reduce psychotic symptoms by blocking dopamine receptors.",
    "Mood Stabilizers": "Medications that reduce mood swings in bipolar disorder (e.g., lithium).",
    "ECT": "Electroconvulsive Therapy - a treatment using brief electrical stimulation of the brain for severe depression.",
    "TMS": "Transcranial Magnetic Stimulation - using magnetic pulses to stimulate brain regions.",
    "Pharmacotherapy": "The treatment of disorders with medications.",
    "Meta-Analysis": "A statistical technique combining results from multiple studies.",
    "Efficacy": "Whether a treatment works in controlled research settings.",
    "Effectiveness": "Whether a treatment works in real-world clinical settings.",
    "Common Factors": "Elements shared by most therapies that contribute to effectiveness (alliance, hope, etc.).",
    "Placebo Effect": "Improvement resulting from expectations rather than the treatment itself."
};

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = TERM_DEFINITIONS;
}
